#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""energy_fault_detector documentation build configuration file.

created by ``sphinx-quickstart`` on Fri Feb  9 13:32:39 2018 and heavily modified.

This file is execfile()d with the current directory set to its containing dir.

Note that not all possible configuration values are present in this autogenerated file.

All configuration values have a default; values that are commented out serve to show the default.

If extensions (or modules to document with autodoc) are in another directory,
add these directories to sys.path here. If the directory is relative to the documentation root,
use os.path.abspath to make it absolute, like shown here.

"""
import os
import sys
import inspect
import importlib

IMPORT_NAME = 'energy_fault_detector'  # name used for imports

# Ensure the project/package is importable when building docs from a source tree
HERE = os.path.dirname(__file__)
PROJECT_ROOT = os.path.dirname(HERE)
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

from energy_fault_detector import __about__ as about  # noqa: E402

# Add the path of our module to the import searchpath (uncomment to use)
# import sys
# sys.path.insert(0, os.path.abspath('..'))

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# Example configuration for intersphinx: refer to the Python standard library.
# intersphinx_mapping = {'<name>': ('https://docs.python.org/', None)}

add_module_names = False

autodoc_mock_imports = ["sklearn"]

# Silence warnings about unresolved external labels in third-party docstrings (e.g. sklearn)
suppress_warnings = [
    "ref.ref",  # undefined :ref: targets
]

autoclass_content = 'both'

# ======================================================================================
# No configurable options below this line


# current version etc. -----------------------------------------------------------------
version = about.__version__

# -- General configuration -------------------------------------------------------------
# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',        # generate docs from docstrings
    'sphinx.ext.napoleon',       # does some formatting tricks
    'sphinx_autodoc_typehints',  # package needs to be installed
    'sphinx.ext.imgmath',        # render latex graphics
    'sphinx_copybutton',         # add copy button to code blocks
    'sphinx.ext.autosummary',
    'sphinx.ext.linkcode',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = about.__title__
copyright = about.__copyright__
author = ', '.join(about.__author__)

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short deviations.Y version.
# Get current version from the version file
# The full version, including alpha/beta/rc tags.
release = version  # (we don't use any such tags)

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todoList` produce output, else they produce nothing.
todo_include_todos = False
autodoc_warningiserror = False  # Some warnings can happen

# -- Options for Napoleon extension ---------------------------------------
# Allow Google style docstrings, but disallow Numpy style docstrings.
# For the sake of consistency it is a good idea not to mix those.
napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True

napoleon_type_aliases = {
    "Config": "energy_fault_detector.Config",
    "FaultDetector": "energy_fault_detector.FaultDetector",
}

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

html_context = {
    "display_github": True,
    "github_user": "AEFDI",
    "github_repo": "EnergyFaultDetector",
    "github_version": "main",
    "conf_py_path": "/docs/",
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
html_favicon = '_static/favicon.ico'
html_logo = '_static/logo.png'

# These paths are either relative to html_static_path
# or fully qualified paths (eg. https://...)
html_css_files = [
    'custom.css',
]

# -- Options for HTMLHelp output ------------------------------------------
# Output file base name for HTML help builder.
htmlhelp_basename = 'pydoc'

html_title = f"{project} documentation"

# -- Options for LaTeX output ---------------------------------------------
latex_elements = {}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [(
    master_doc,
    IMPORT_NAME + '.tex',
    about.__title__ + ' Documentation',
    ', '.join(about.__author__), 'manual'
)]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(
    master_doc,
    IMPORT_NAME,
    about.__title__ + ' Documentation',
    about.__author__, 1)
]

# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, about.__title__, about.__title__ + ' Documentation',
     about.__author__, about.__title__, about.__description__,
     'Miscellaneous'),
]


def run_apidoc(app):
    """Generate API .rst files with sphinx-apidoc, like in CI:

       sphinx-apidoc -o docs energy_fault_detector/ --module-first --force --separate --templatedir docs/_templates
    """

    # Only run this step if we're building the HTML docs
    if app.builder.name != "html":
        return

    from sphinx.ext.apidoc import main as apidoc_main
    from pathlib import Path

    here = Path(__file__).parent
    pkg_dir = here.parent / IMPORT_NAME
    out_dir = here
    templates = here / "_templates"

    apidoc_main([
        "-o", str(out_dir),
        str(pkg_dir),
        "--module-first",
        "--force",
        "--separate",
        "--templatedir", str(templates),
        # Following files are skipped
        # Quick fault detection internals
        str(pkg_dir / "main.py"),
        str(pkg_dir / "quick_fault_detection" / "configuration.py"),
        str(pkg_dir / "quick_fault_detection" / "data_loading.py"),
        str(pkg_dir / "quick_fault_detection" / "optimization.py"),
        str(pkg_dir / "quick_fault_detection" / "output.py"),
        str(pkg_dir / "quick_fault_detection" / "pipeline.py"),
        str(pkg_dir / "quick_fault_detection" / "quick_fault_detector.py"),
        # core internals
        str(pkg_dir / "core" / "anomaly_score.py"),
        str(pkg_dir / "core" / "data_transformer.py"),
        str(pkg_dir / "core" / "threshold_selector.py"),
        str(pkg_dir / "core" / "fault_detection_result.py"),
        str(pkg_dir / "core" / "fault_detection_model.py"),
        str(pkg_dir / "core" / "model_factory.py"),
        str(pkg_dir / "core" / "save_load_mixin.py"),
        # internal utilities
        str(pkg_dir / "utils" / "index_utils.py"),
        # config internals
        str(pkg_dir / "config" / "base_config.py"),
        str(pkg_dir / "config" / "config.py"),
        str(pkg_dir / "config" / "quickstart_config.py"),
        # Class specific files (documented directly under the top module)
        # autoencoder
        str(pkg_dir / "autoencoders" / "multilayer_autoencoder.py"),
        str(pkg_dir / "autoencoders" / "conditional_autoencoder.py"),
        str(pkg_dir / "autoencoders" / "lstm_seq2one_autoencoder.py"),
        str(pkg_dir / "autoencoders" / "cnn_seq2one_autoencoder.py"),
        str(pkg_dir / "autoencoders" / "bidirectional_lstm_seq2one_autoencoder.py"),
        str(pkg_dir / "autoencoders" / "cnn_seq_autoencoder.py"),
        str(pkg_dir / "autoencoders" / "lstm_seq2seq_autoencoder.py"),
        # anomaly score
        str(pkg_dir / "anomaly_scores" / "rmse_score.py"),
        str(pkg_dir / "anomaly_scores" / "mahalanobis_score.py"),
        # threshold selector
        str(pkg_dir / "threshold_selectors" / "adaptive_threshold.py"),
        str(pkg_dir / "threshold_selectors" / "fdr_threshold.py"),
        str(pkg_dir / "threshold_selectors" / "fbeta_threshold.py"),
        str(pkg_dir / "threshold_selectors" / "quantile_threshold.py"),
        # main class (documented directly under the top module)
        str(pkg_dir / "fault_detector.py"),
    ])


def setup(app):
    app.connect("builder-inited", run_apidoc)


def linkcode_resolve(domain, info):
    if domain != "py" or not info["module"]:
        return None
    try:
        mod = importlib.import_module(info["module"])
        obj = mod
        for part in info["fullname"].split("."):
            obj = getattr(obj, part)
        obj = inspect.unwrap(obj)
        source_file = inspect.getsourcefile(obj)
        source_lines, start_line = inspect.getsourcelines(obj)
    except (TypeError, OSError, AttributeError):
        return None
    if source_file is None:
        return None

    source_file = os.path.relpath(source_file, start=PROJECT_ROOT)
    if not source_file.startswith(IMPORT_NAME + os.sep):
        return None

    source_file = source_file.replace(os.sep, "/")
    end_line = start_line + len(source_lines) - 1
    return (
        f"https://github.com/AEFDI/EnergyFaultDetector/blob/main/"
        f"{source_file}#L{start_line}-L{end_line}"
    )
